name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cache-dealii:
    runs-on: ubuntu-latest
    container: rockylinux:8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yum update -y
        yum groupinstall -y "Development Tools"
        yum install -y epel-release cmake wget gcc gcc-c++ make git

        # Enable 'powertools' for additional dependencies
        yum config-manager --set-enabled powertools

        # Install required libraries for deal.II and UMFPACK
        yum install -y libaec libaec-devel blas lapack hdf5 hdf5-devel boost boost-devel \
                       suitesparse-devel metis metis-devel mpi mpi-devel

    - name: Download deal.II tarball
      run: wget https://dealii.org/downloads/dealii-9.5.1.tar.gz

    - name: Cache deal.II installation
      id: cache-dealii
      uses: actions/cache@v3
      with:
        path: ~/dealii
        key: dealii-9.5.1-with-umfpack-${{ runner.os }}-${{ hashFiles('dealii-9.5.1.tar.gz') }}
        restore-keys: |
          dealii-9.5.1-with-umfpack-${{ runner.os }}-

    - name: Install deal.II (if not cached)
      if: steps.cache-dealii.outputs.cache-hit != 'true'
      run: |
        tar -xzf dealii-9.5.1.tar.gz
        cd dealii-9.5.1
        cmake -DCMAKE_INSTALL_PREFIX=~/dealii \
              -DDEAL_II_WITH_UMFPACK=ON \
              -DDEAL_II_WITH_MPI=OFF \
              -DDEAL_II_WITH_P4EST=OFF \
              -DUMFPACK_DIR=/usr \
              -DMETIS_DIR=/usr .
        make -j$(nproc)
        make install
        cd ..

    - name: Verify deal.II Cache
      run: |
        if [ -d "~/dealii" ]; then
          echo "deal.II is cached in ~/dealii."
        else
          echo "deal.II directory not found!"
        fi

  build-and-test:
    runs-on: ubuntu-latest
    container: rockylinux:8
    needs: cache-dealii

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yum update -y
        yum groupinstall -y "Development Tools"
        yum install -y epel-release cmake wget gcc gcc-c++ make git

        # Enable 'powertools' for additional dependencies
        yum config-manager --set-enabled powertools

        # Install required libraries for deal.II and UMFPACK
        yum install -y libaec libaec-devel blas lapack hdf5 hdf5-devel boost boost-devel \
                       suitesparse-devel metis metis-devel mpi mpi-devel

    - name: Restore Cache for deal.II
      uses: actions/cache@v3
      with:
        path: ~/dealii
        key: dealii-9.5.1-with-umfpack-${{ runner.os }}-${{ hashFiles('dealii-9.5.1.tar.gz') }}
        restore-keys: |
          dealii-9.5.1-with-umfpack-${{ runner.os }}-

    - name: Set up environment variables for deal.II
      run: |
        export DEAL_II_DIR=~/dealii
        echo "DEAL_II_DIR=$DEAL_II_DIR" >> $GITHUB_ENV

    - name: Install DOpElib
      run: |
        # Install DOpElib from GitHub
        git clone https://github.com/winnifried/dopelib.git
        cd dopelib/DOpEsrc

        # Set the environment variable before running the configuration script
        export DEAL_II_DIR=$DEAL_II_DIR
        
        # Run the autocmake.sh script with the correct arguments
        ./autocmake.sh configure
        make c-all

        # Manually copy the compiled libraries to the installation directory
        mkdir -p ~/dopelib/lib
        cp autobuild/release/libdope.a ~/dopelib/lib/
        cp autobuild/debug/libdope.a ~/dopelib/lib/

        # Copy headers if necessary
        mkdir -p ~/dopelib/include
        cp -r ../include/* ~/dopelib/include/
        cd ../..

    - name: Build the project
      run: |
        # Set up environment variables
        export DEAL_II_DIR=~/dealii
        export DOPELIB_DIR=~/dopelib

        # Compile your project
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: ./run_tests.sh