name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cache-dealii:
    runs-on: ubuntu-latest
    container: rockylinux:8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yum update -y
        yum groupinstall -y "Development Tools"
        yum install -y epel-release cmake wget gcc gcc-c++ make git

    - name: Build and Install libaec from Source
      run: |
        wget https://gitlab.dkrz.de/k202009/libaec/-/archive/v1.0.6/libaec-v1.0.6.tar.gz
        tar -xzf libaec-v1.0.6.tar.gz
        cd libaec-v1.0.6
        mkdir build && cd build
        cmake ..
        make
        make install
        cd ../..

    - name: Install remaining dependencies
      run: |
        yum install -y hdf5 hdf5-devel --nobest
        yum install -y blas lapack boost boost-devel suitesparse

    - name: Download deal.II tarball
      run: |
        wget https://dealii.org/downloads/dealii-9.5.1.tar.gz

    - name: Cache deal.II installation
      id: cache-dealii
      uses: actions/cache@v3
      with:
        path: ~/dealii
        key: dealii-9.5.1-with-umfpack-${{ runner.os }}-${{ hashFiles('dealii-9.5.1.tar.gz') }}
        restore-keys: |
          dealii-9.5.1-with-umfpack-${{ runner.os }}-

    - name: Install deal.II (if not cached)
      if: steps.cache-dealii.outputs.cache-hit != 'true'
      run: |
        tar -xzf dealii-9.5.1.tar.gz
        cd dealii-9.5.1
        cmake -DCMAKE_INSTALL_PREFIX=~/dealii -DDEAL_II_WITH_UMFPACK=ON -DDEAL_II_WITH_LAPACK=ON .
        make -j$(nproc)
        make install
        cd ..

    - name: Verify deal.II Cache and Set Environment Variable
      run: |
        if [ -d "~/dealii" ]; then
          echo "deal.II is cached in ~/dealii."
          echo "DEAL_II_DIR=~/dealii" >> $GITHUB_ENV
        else
          echo "deal.II directory not found!"
        fi

  build-and-test:
    runs-on: ubuntu-latest
    container: rockylinux:8
    needs: cache-dealii

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yum update -y
        yum install -y epel-release cmake wget gcc gcc-c++ make git blas lapack hdf5 hdf5-devel boost boost-devel suitesparse

    - name: Restore Cache for deal.II
      uses: actions/cache@v3
      with:
        path: ~/dealii
        key: dealii-9.5.1-with-umfpack-${{ runner.os }}-${{ hashFiles('dealii-9.5.1.tar.gz') }}
        restore-keys: |
          dealii-9.5.1-with-umfpack-${{ runner.os }}-

    - name: Check DEAL_II_DIR Environment Variable
      run: echo "DEAL_II_DIR is set to: $DEAL_II_DIR"

    - name: Install DOpElib
      run: |
        # Clone DOpElib from GitHub
        git clone https://github.com/winnifried/dopelib.git
        cd dopelib/DOpEsrc

        # Check the DEAL_II_DIR setting
        echo "DEAL_II_DIR is set to: $DEAL_II_DIR"

        # Run the autocmake.sh script to configure DOpElib
        ./autocmake.sh configure

        # Build DOpElib using make c-all as per the guide
        make c-all

        # Check if the build was successful and copy the libraries
        mkdir -p ~/dopelib/lib
        if [ -f autobuild/release/libdope.a ]; then
          cp autobuild/release/libdope.a ~/dopelib/lib/
        else
          echo "Release library libdope.a not found!"
        fi

        if [ -f autobuild/debug/libdope.a ]; then
          cp autobuild/debug/libdope.a ~/dopelib/lib/
        else
          echo "Debug library libdope.a not found!"
        fi

        # Copy headers to the installation directory
        mkdir -p ~/dopelib/include
        cp -r ../include/* ~/dopelib/include/
        cd ../..

    - name: Build the project
      run: |
        # Set up environment variables
        export DEAL_II_DIR=~/dealii
        export DOPELIB_DIR=~/dopelib
        
        # Compile your project
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        # Run your test script
        ./run_tests.sh